import {
  Customer,
  OrderItem,
  Rider,
  InventoryItem,
  WalletTransaction,
  DeliveryRoute,
  SubscriptionPlanItem,
  ServiceAreaInfo,
  RazorpayReconciliation,
  AuditLogItem,
  RaipurZone
} from '@/types';

export const RAIPUR_AREAS: RaipurZone[] = [
  'Shankar Nagar',
  'Telibandha',
  'Samta Colony',
  'Pandri',
  'Civil Lines',
  'Devendra Nagar',
  'Tatibandh',
  'Pachpedi Naka',
  'VIP Road'
];

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: 'CUST-1001',
    name: 'Ananya Sharma',
    phone: '+91 98261 44521',
    area: 'Shankar Nagar',
    address: 'B-14, Green Valley Enclave, Sector 2, Shankar Nagar',
    walletBalance: 840,
    planType: 'Daily',
    planStatus: 'Active',
    buyOnceLimitOverride: 1500,
    bottleDepositCount: 4,
    activeSince: '2025-08-12',
  },
  {
    id: 'CUST-1002',
    name: 'Vikram Agrawal',
    phone: '+91 94252 88123',
    area: 'Telibandha',
    address: 'Flat 402, Anandam Imperial, VIP Chowk, Telibandha',
    walletBalance: 120, // Below threshold of ₹180!
    planType: 'Daily',
    planStatus: 'Active',
    buyOnceLimitOverride: 500,
    bottleDepositCount: 2,
    activeSince: '2025-11-04',
  },
  {
    id: 'CUST-1003',
    name: 'Priyanka Dewangan',
    phone: '+91 97555 19022',
    area: 'Civil Lines',
    address: 'Bungalow 7, Officers Colony, Near Raj Bhavan, Civil Lines',
    walletBalance: 2450,
    planType: '7-Day Trial',
    planStatus: 'Active',
    buyOnceLimitOverride: 2000,
    bottleDepositCount: 1,
    activeSince: '2026-09-28',
    trialExpiresAt: '2026-10-05',
  },
  {
    id: 'CUST-1004',
    name: 'Rajesh Baghel',
    phone: '+91 98271 63490',
    area: 'Samta Colony',
    address: 'House 82, Street 4, Near Agrasen Bhawan, Samta Colony',
    walletBalance: 1620,
    planType: 'Alternate',
    planStatus: 'Active',
    buyOnceLimitOverride: 1000,
    bottleDepositCount: 3,
    activeSince: '2025-05-19',
  },
  {
    id: 'CUST-1005',
    name: 'Dr. Sunita Shukla',
    phone: '+91 94060 21544',
    area: 'Devendra Nagar',
    address: 'HIG-21, Sector 4, Opposite Katora Talab Park, Devendra Nagar',
    walletBalance: 45, // Critical low
    planType: 'Daily',
    planStatus: 'Active',
    buyOnceLimitOverride: 0,
    bottleDepositCount: 2,
    activeSince: '2025-09-10',
  },
  {
    id: 'CUST-1006',
    name: 'Harish Jain',
    phone: '+91 91114 78901',
    area: 'Pandri',
    address: 'Shop & Residence 12, Cloth Market Complex, Pandri',
    walletBalance: 980,
    planType: 'Buy Once',
    planStatus: 'Active',
    buyOnceLimitOverride: 3000,
    bottleDepositCount: 0,
    activeSince: '2026-01-15',
  },
  {
    id: 'CUST-1007',
    name: 'Kavita Verma',
    phone: '+91 97520 33411',
    area: 'VIP Road',
    address: 'Villa 18, Palm Greens, Near Airport Turning, VIP Road',
    walletBalance: 3200,
    planType: 'Daily',
    planStatus: 'Active',
    buyOnceLimitOverride: 2500,
    bottleDepositCount: 6,
    activeSince: '2025-04-01',
  },
  {
    id: 'CUST-1008',
    name: 'Abhishek Singhania',
    phone: '+91 98930 11200',
    area: 'Shankar Nagar',
    address: 'Penthouse 10A, Ashoka Millennium, Shankar Nagar Main Road',
    walletBalance: 1850,
    planType: '7-Day Trial',
    planStatus: 'Active',
    buyOnceLimitOverride: 1500,
    bottleDepositCount: 1,
    activeSince: '2026-10-01',
    trialExpiresAt: '2026-10-08',
  },
  {
    id: 'CUST-1009',
    name: 'Meena Chandrakar',
    phone: '+91 93001 45892',
    area: 'Tatibandh',
    address: 'Qtr C-9, AIIMS Campus Colony, GE Road, Tatibandh',
    walletBalance: 510,
    planType: 'Alternate',
    planStatus: 'Active',
    buyOnceLimitOverride: 500,
    bottleDepositCount: 2,
    activeSince: '2025-10-22',
  },
  {
    id: 'CUST-1010',
    name: 'Nitin Pande',
    phone: '+91 96172 09843',
    area: 'Pachpedi Naka',
    address: 'Plot 34, Shailendra Nagar Extn, Near Pachpedi Flyover',
    walletBalance: 380,
    planType: 'Daily',
    planStatus: 'Paused',
    buyOnceLimitOverride: 500,
    bottleDepositCount: 3,
    activeSince: '2025-06-30',
  },
  {
    id: 'CUST-1011',
    name: 'Ritika Kothari',
    phone: '+91 98263 77410',
    area: 'Samta Colony',
    address: '504, Vardhman Towers, Agrasen Chowk, Samta Colony',
    walletBalance: 1420,
    planType: 'Daily',
    planStatus: 'Active',
    buyOnceLimitOverride: 1200,
    bottleDepositCount: 4,
    activeSince: '2025-07-14',
  },
  {
    id: 'CUST-1012',
    name: 'Suresh Banchhor',
    phone: '+91 94241 62901',
    area: 'Telibandha',
    address: 'B-6, Marine Drive View Apartments, Telibandha Lake Front',
    walletBalance: 760,
    planType: '7-Day Trial',
    planStatus: 'Active',
    buyOnceLimitOverride: 800,
    bottleDepositCount: 1,
    activeSince: '2026-09-30',
    trialExpiresAt: '2026-10-07',
  }
];

export const MOCK_RIDERS: Rider[] = [
  {
    id: 'RIDER-01',
    name: 'Ramesh Verma',
    phone: '+91 98270 54109',
    assignedArea: 'Shankar Nagar',
    vehicleNumber: 'CG 04 MT 8821',
    status: 'Active',
    stopsCount: 34,
    capacityCrates: 6,
    rating: 4.9,
  },
  {
    id: 'RIDER-02',
    name: 'Karan Sahu',
    phone: '+91 97550 12890',
    assignedArea: 'Telibandha',
    vehicleNumber: 'CG 04 NZ 4410',
    status: 'Active',
    stopsCount: 29,
    capacityCrates: 5,
    rating: 4.8,
  },
  {
    id: 'RIDER-03',
    name: 'Sunil Yadav',
    phone: '+91 99071 88342',
    assignedArea: 'Civil Lines',
    vehicleNumber: 'CG 04 KA 1902',
    status: 'Active',
    stopsCount: 26,
    capacityCrates: 5,
    rating: 4.95,
  },
  {
    id: 'RIDER-04',
    name: 'Bhupendra Dewangan',
    phone: '+91 91792 65431',
    assignedArea: 'Samta Colony',
    vehicleNumber: 'CG 04 LR 9011',
    status: 'Active',
    stopsCount: 31,
    capacityCrates: 6,
    rating: 4.75,
  },
  {
    id: 'RIDER-05',
    name: 'Manoj Baghel',
    phone: '+91 93010 44921',
    assignedArea: 'Pandri',
    vehicleNumber: 'CG 04 PK 6720',
    status: 'Active',
    stopsCount: 22,
    capacityCrates: 4,
    rating: 4.85,
  },
  {
    id: 'RIDER-06',
    name: 'Dinesh Kurre',
    phone: '+91 94076 81190',
    assignedArea: 'Devendra Nagar',
    vehicleNumber: 'CG 04 JB 3319',
    status: 'Active',
    stopsCount: 25,
    capacityCrates: 5,
    rating: 4.7,
  },
  {
    id: 'RIDER-07',
    name: 'Prakash Soni',
    phone: '+91 96914 23091',
    assignedArea: 'Unassigned',
    vehicleNumber: 'CG 04 KH 7712',
    status: 'Off Duty',
    stopsCount: 0,
    capacityCrates: 5,
    rating: 4.8,
  },
  {
    id: 'RIDER-08',
    name: 'Amit Tandi',
    phone: '+91 98269 90812',
    assignedArea: 'Unassigned',
    vehicleNumber: 'CG 04 QM 5501',
    status: 'Active',
    stopsCount: 0,
    capacityCrates: 5,
    rating: 4.9,
  }
];

export const MOCK_ROUTES: DeliveryRoute[] = [
  {
    id: 'ROUTE-SN',
    zone: 'Shankar Nagar',
    pincode: '492007',
    assignedRiderId: 'RIDER-01',
    assignedRiderName: 'Ramesh Verma',
    vehicleNumber: 'CG 04 MT 8821',
    stopsCount: 34,
    litersRequired: 88,
    cratesCount: 6,
    status: 'Assigned',
    targetDeparture: '05:30 AM',
  },
  {
    id: 'ROUTE-TB',
    zone: 'Telibandha',
    pincode: '492006',
    assignedRiderId: 'RIDER-02',
    assignedRiderName: 'Karan Sahu',
    vehicleNumber: 'CG 04 NZ 4410',
    stopsCount: 29,
    litersRequired: 74,
    cratesCount: 5,
    status: 'Assigned',
    targetDeparture: '05:30 AM',
  },
  {
    id: 'ROUTE-CL',
    zone: 'Civil Lines',
    pincode: '492001',
    assignedRiderId: 'RIDER-03',
    assignedRiderName: 'Sunil Yadav',
    vehicleNumber: 'CG 04 KA 1902',
    stopsCount: 26,
    litersRequired: 68,
    cratesCount: 5,
    status: 'Assigned',
    targetDeparture: '05:45 AM',
  },
  {
    id: 'ROUTE-SC',
    zone: 'Samta Colony',
    pincode: '492001',
    assignedRiderId: 'RIDER-04',
    assignedRiderName: 'Bhupendra Dewangan',
    vehicleNumber: 'CG 04 LR 9011',
    stopsCount: 31,
    litersRequired: 79,
    cratesCount: 6,
    status: 'Assigned',
    targetDeparture: '05:30 AM',
  },
  {
    id: 'ROUTE-PD',
    zone: 'Pandri',
    pincode: '492004',
    assignedRiderId: 'RIDER-05',
    assignedRiderName: 'Manoj Baghel',
    vehicleNumber: 'CG 04 PK 6720',
    stopsCount: 22,
    litersRequired: 56,
    cratesCount: 4,
    status: 'Assigned',
    targetDeparture: '06:00 AM',
  },
  {
    id: 'ROUTE-DN',
    zone: 'Devendra Nagar',
    pincode: '492004',
    assignedRiderId: 'RIDER-06',
    assignedRiderName: 'Dinesh Kurre',
    vehicleNumber: 'CG 04 JB 3319',
    stopsCount: 25,
    litersRequired: 64,
    cratesCount: 5,
    status: 'Assigned',
    targetDeparture: '05:45 AM',
  },
  {
    id: 'ROUTE-TBH',
    zone: 'Tatibandh',
    pincode: '492099',
    assignedRiderId: null,
    assignedRiderName: null,
    vehicleNumber: null,
    stopsCount: 18,
    litersRequired: 42,
    cratesCount: 3,
    status: 'Unassigned', // Warning flag!
    targetDeparture: '06:00 AM',
  },
  {
    id: 'ROUTE-PN',
    zone: 'Pachpedi Naka',
    pincode: '492001',
    assignedRiderId: null,
    assignedRiderName: null,
    vehicleNumber: null,
    stopsCount: 16,
    litersRequired: 38,
    cratesCount: 3,
    status: 'Unassigned', // Warning flag!
    targetDeparture: '06:15 AM',
  },
  {
    id: 'ROUTE-VIP',
    zone: 'VIP Road',
    pincode: '492015',
    assignedRiderId: 'RIDER-08',
    assignedRiderName: 'Amit Tandi',
    vehicleNumber: 'CG 04 QM 5501',
    stopsCount: 15,
    litersRequired: 45,
    cratesCount: 3,
    status: 'Assigned',
    targetDeparture: '06:15 AM',
  }
];

export const MOCK_ORDERS: OrderItem[] = [
  {
    id: 'ORD-2026-901',
    customerName: 'Ananya Sharma',
    phone: '+91 98261 44521',
    area: 'Shankar Nagar',
    address: 'B-14, Green Valley Enclave, Sector 2',
    product: 'A2 Desi Cow Milk',
    quantity: '2 Liters (1L x 2 Glass Bottles)',
    type: 'Daily',
    status: 'Pending',
    riderId: 'RIDER-01',
    riderName: 'Ramesh Verma',
    deliveryNotes: 'Keep inside milk box next to main gate, ring bell once',
    amount: 180,
    timeSlot: '06:00 AM - 07:00 AM',
    batchTimestamp: 'Tonight 10:00 PM',
  },
  {
    id: 'ORD-2026-902',
    customerName: 'Vikram Agrawal',
    phone: '+91 94252 88123',
    area: 'Telibandha',
    address: 'Flat 402, Anandam Imperial, VIP Chowk',
    product: 'A2 Desi Cow Milk',
    quantity: '1 Liter (1L Glass Bottle)',
    type: 'Daily',
    status: 'Skipped', // Low wallet balance!
    riderId: 'RIDER-02',
    riderName: 'Karan Sahu',
    deliveryNotes: 'Low Wallet Balance ₹120 (Min ₹180 required). Auto-skipped by 10 PM Engine.',
    amount: 90,
    timeSlot: '06:30 AM - 07:30 AM',
    batchTimestamp: 'Tonight 10:00 PM',
  },
  {
    id: 'ORD-2026-903',
    customerName: 'Priyanka Dewangan',
    phone: '+91 97555 19022',
    area: 'Civil Lines',
    address: 'Bungalow 7, Officers Colony, Near Raj Bhavan',
    product: 'A2 Desi Cow Milk + A2 Vedic Bilona Ghee',
    quantity: '1.5 Liters Milk + 500ml Ghee Jar',
    type: '7-Day Trial',
    status: 'Pending',
    riderId: 'RIDER-03',
    riderName: 'Sunil Yadav',
    deliveryNotes: 'Trial Day 6. Handover to security guard Mr. Ramu',
    amount: 1055,
    timeSlot: '06:00 AM - 07:00 AM',
    batchTimestamp: 'Tonight 10:00 PM',
  },
  {
    id: 'ORD-2026-904',
    customerName: 'Rajesh Baghel',
    phone: '+91 98271 63490',
    area: 'Samta Colony',
    address: 'House 82, Street 4, Near Agrasen Bhawan',
    product: 'A2 Desi Cow Milk + Farm Fresh A2 Paneer',
    quantity: '2 Liters Milk + 200g Paneer',
    type: 'Alternate',
    status: 'Pending',
    riderId: 'RIDER-04',
    riderName: 'Bhupendra Dewangan',
    deliveryNotes: 'Collect empty glass bottle from milk bag',
    amount: 280,
    timeSlot: '05:45 AM - 06:45 AM',
    batchTimestamp: 'Tonight 10:00 PM',
  },
  {
    id: 'ORD-2026-905',
    customerName: 'Dr. Sunita Shukla',
    phone: '+91 94060 21544',
    area: 'Devendra Nagar',
    address: 'HIG-21, Sector 4, Opposite Katora Talab Park',
    product: 'A2 Desi Cow Milk',
    quantity: '1 Liter',
    type: 'Daily',
    status: 'Skipped', // Low wallet
    riderId: 'RIDER-06',
    riderName: 'Dinesh Kurre',
    deliveryNotes: 'Insufficient balance (₹45 remaining). SMS reminder sent at 08:30 PM.',
    amount: 90,
    timeSlot: '06:15 AM - 07:15 AM',
    batchTimestamp: 'Tonight 10:00 PM',
  },
  {
    id: 'ORD-2026-906',
    customerName: 'Harish Jain',
    phone: '+91 91114 78901',
    area: 'Pandri',
    address: 'Shop & Residence 12, Cloth Market Complex',
    product: 'A2 Vedic Bilona Ghee (1L Glass Jar)',
    quantity: '1 Liter Glass Jar',
    type: 'Buy Once',
    status: 'Pending',
    riderId: 'RIDER-05',
    riderName: 'Manoj Baghel',
    deliveryNotes: 'Careful handling - glass jar with festive seal',
    amount: 1850,
    timeSlot: '07:00 AM - 08:00 AM',
    batchTimestamp: 'Tonight 10:00 PM',
  },
  {
    id: 'ORD-2026-907',
    customerName: 'Kavita Verma',
    phone: '+91 97520 33411',
    area: 'VIP Road',
    address: 'Villa 18, Palm Greens, Near Airport Turning',
    product: 'A2 Desi Cow Milk + Fresh A2 Dahi',
    quantity: '3 Liters Milk + 500g Dahi Cup',
    type: 'Daily',
    status: 'Pending',
    riderId: 'RIDER-08',
    riderName: 'Amit Tandi',
    deliveryNotes: 'VIP gated community, use entry QR code at barrier',
    amount: 390,
    timeSlot: '06:30 AM - 07:30 AM',
    batchTimestamp: 'Tonight 10:00 PM',
  },
  {
    id: 'ORD-2026-908',
    customerName: 'Abhishek Singhania',
    phone: '+91 98930 11200',
    area: 'Shankar Nagar',
    address: 'Penthouse 10A, Ashoka Millennium, Shankar Nagar Main Road',
    product: 'A2 Desi Cow Milk (7-Day Trial)',
    quantity: '1 Liter (1L Bottle)',
    type: '7-Day Trial',
    status: 'Pending',
    riderId: 'RIDER-01',
    riderName: 'Ramesh Verma',
    deliveryNotes: 'Trial Day 3. Leave on door-hook',
    amount: 90,
    timeSlot: '06:15 AM - 07:15 AM',
    batchTimestamp: 'Tonight 10:00 PM',
  },
  {
    id: 'ORD-2026-909',
    customerName: 'Meena Chandrakar',
    phone: '+91 93001 45892',
    area: 'Tatibandh',
    address: 'Qtr C-9, AIIMS Campus Colony, GE Road',
    product: 'A2 Desi Cow Milk + White Butter',
    quantity: '2 Liters Milk + 250g Makkhan',
    type: 'Alternate',
    status: 'Pending',
    riderId: null, // Unassigned rider alert!
    riderName: null,
    deliveryNotes: 'Tatibandh Route unassigned! Must be allocated before 05:00 AM dispatch',
    amount: 360,
    timeSlot: '06:45 AM - 07:45 AM',
    batchTimestamp: 'Tonight 10:00 PM',
  },
  {
    id: 'ORD-2026-910',
    customerName: 'Ritika Kothari',
    phone: '+91 98263 77410',
    area: 'Samta Colony',
    address: '504, Vardhman Towers, Agrasen Chowk',
    product: 'A2 Desi Cow Milk + Farm Fresh A2 Paneer',
    quantity: '2 Liters Milk + 500g Paneer Block',
    type: 'Daily',
    status: 'Pending',
    riderId: 'RIDER-04',
    riderName: 'Bhupendra Dewangan',
    deliveryNotes: 'Apartment lift available. Bell rings softly.',
    amount: 420,
    timeSlot: '06:00 AM - 07:00 AM',
    batchTimestamp: 'Tonight 10:00 PM',
  },
  {
    id: 'ORD-2026-911',
    customerName: 'Suresh Banchhor',
    phone: '+91 94241 62901',
    area: 'Telibandha',
    address: 'B-6, Marine Drive View Apartments',
    product: 'A2 Desi Cow Milk',
    quantity: '1 Liter',
    type: '7-Day Trial',
    status: 'Pending',
    riderId: 'RIDER-02',
    riderName: 'Karan Sahu',
    deliveryNotes: 'Trial Day 4. Customer requested delivery before 07:00 AM',
    amount: 90,
    timeSlot: '06:00 AM - 06:45 AM',
    batchTimestamp: 'Tonight 10:00 PM',
  },
  {
    id: 'ORD-2026-912',
    customerName: 'Nitin Pande',
    phone: '+91 96172 09843',
    area: 'Pachpedi Naka',
    address: 'Plot 34, Shailendra Nagar Extn',
    product: 'A2 Desi Cow Milk',
    quantity: '1.5 Liters',
    type: 'Daily',
    status: 'Skipped', // Plan paused
    riderId: null,
    riderName: null,
    deliveryNotes: 'Subscription paused by customer until Oct 10th (Out of station)',
    amount: 135,
    timeSlot: '06:30 AM - 07:30 AM',
    batchTimestamp: 'Tonight 10:00 PM',
  }
];

export const MOCK_INVENTORY: InventoryItem[] = [
  {
    id: 'INV-A2-1L',
    name: 'A2 Desi Gir Cow Milk (1L Bottle)',
    unit: '1L Glass Bottle',
    currentStock: 520,
    tomorrowRequired: 482,
    threshold: 450,
    status: 'Optimal',
    batchCode: 'PF-MILK-OCT05-AM',
    shelfLifeDays: 2,
    category: 'Fresh Milk',
  },
  {
    id: 'INV-A2-500ML',
    name: 'A2 Desi Gir Cow Milk (500ml Bottle)',
    unit: '500ml Glass Bottle',
    currentStock: 95,
    tomorrowRequired: 90,
    threshold: 80,
    status: 'Optimal',
    batchCode: 'PF-MILK-500-OCT05',
    shelfLifeDays: 2,
    category: 'Fresh Milk',
  },
  {
    id: 'INV-GHEE-1L',
    name: 'A2 Vedic Bilona Ghee (1L Glass Jar)',
    unit: '1L Jar',
    currentStock: 14,
    tomorrowRequired: 18,
    threshold: 25,
    status: 'Low Stock', // Alert!
    batchCode: 'PF-GHEE-SEP28',
    shelfLifeDays: 180,
    category: 'Clarified Butter',
  },
  {
    id: 'INV-GHEE-500ML',
    name: 'A2 Vedic Bilona Ghee (500ml Glass Jar)',
    unit: '500ml Jar',
    currentStock: 28,
    tomorrowRequired: 22,
    threshold: 20,
    status: 'Optimal',
    batchCode: 'PF-GHEE-SEP28',
    shelfLifeDays: 180,
    category: 'Clarified Butter',
  },
  {
    id: 'INV-PANEER-200G',
    name: 'Farm Fresh A2 Paneer (200g Vacuum Pack)',
    unit: '200g Pack',
    currentStock: 35,
    tomorrowRequired: 42,
    threshold: 40,
    status: 'Critical', // Under required!
    batchCode: 'PF-PAN-OCT04-EVE',
    shelfLifeDays: 4,
    category: 'Artisanal Cheese',
  },
  {
    id: 'INV-PANEER-500G',
    name: 'Farm Fresh A2 Paneer (500g Vacuum Pack)',
    unit: '500g Pack',
    currentStock: 26,
    tomorrowRequired: 20,
    threshold: 15,
    status: 'Optimal',
    batchCode: 'PF-PAN-OCT04-EVE',
    shelfLifeDays: 4,
    category: 'Artisanal Cheese',
  },
  {
    id: 'INV-DAHI-500G',
    name: 'Fresh A2 Dahi / Curd (500g Earthen Pot/Cup)',
    unit: '500g Cup',
    currentStock: 64,
    tomorrowRequired: 58,
    threshold: 45,
    status: 'Optimal',
    batchCode: 'PF-DAHI-OCT04',
    shelfLifeDays: 3,
    category: 'Cultured Dairy',
  },
  {
    id: 'INV-BUTTER-250G',
    name: 'Artisanal White Butter / Makkhan (250g)',
    unit: '250g Block',
    currentStock: 12,
    tomorrowRequired: 16,
    threshold: 15,
    status: 'Critical', // Under required!
    batchCode: 'PF-BTR-OCT04',
    shelfLifeDays: 7,
    category: 'Cultured Dairy',
  }
];

export const MOCK_WALLET_TRANSACTIONS: WalletTransaction[] = [
  {
    id: 'WT-88201',
    customerId: 'CUST-1001',
    customerName: 'Ananya Sharma',
    type: 'Auto-Debit',
    amount: 180,
    date: '2026-10-04 22:00:14',
    reason: 'Daily subscription: 2L A2 Milk (Morning 05 Oct delivery)',
    method: 'System Daily Debit',
    referenceId: 'RUN-20261004-2200',
  },
  {
    id: 'WT-88202',
    customerId: 'CUST-1003',
    customerName: 'Priyanka Dewangan',
    type: 'Auto-Debit',
    amount: 1055,
    date: '2026-10-04 22:00:15',
    reason: 'Trial Day 6: 1.5L Milk + 500ml Ghee Jar',
    method: 'System Daily Debit',
    referenceId: 'RUN-20261004-2200',
  },
  {
    id: 'WT-88203',
    customerId: 'CUST-1007',
    customerName: 'Kavita Verma',
    type: 'Credit',
    amount: 3000,
    date: '2026-10-04 18:42:10',
    reason: 'UPI Wallet Top-up (Monthly Float Recharge)',
    method: 'Razorpay',
    referenceId: 'pay_Nq99xKa2891Z',
  },
  {
    id: 'WT-88204',
    customerId: 'CUST-1004',
    customerName: 'Rajesh Baghel',
    type: 'Credit',
    amount: 1500,
    date: '2026-10-04 15:10:02',
    reason: 'Netbanking Top-up (HDFC Bank)',
    method: 'Razorpay',
    referenceId: 'pay_Nq81bWk1044A',
  },
  {
    id: 'WT-88205',
    customerId: 'CUST-1002',
    customerName: 'Vikram Agrawal',
    type: 'Refund',
    amount: 90,
    date: '2026-10-03 11:20:00',
    reason: 'Refund for curd bottle cap leak reported on Oct 3rd',
    method: 'Manual Support',
    referenceId: 'TKT-9912-REFUND',
  },
  {
    id: 'WT-88206',
    customerId: 'CUST-1008',
    customerName: 'Abhishek Singhania',
    type: 'Credit',
    amount: 2000,
    date: '2026-10-03 09:15:30',
    reason: 'Trial pack activation & wallet advance',
    method: 'Razorpay',
    referenceId: 'pay_Np76uX0192L',
  },
  {
    id: 'WT-88207',
    customerId: 'CUST-1011',
    customerName: 'Ritika Kothari',
    type: 'Auto-Debit',
    amount: 420,
    date: '2026-10-04 22:00:18',
    reason: 'Daily subscription: 2L Milk + 500g Paneer',
    method: 'System Daily Debit',
    referenceId: 'RUN-20261004-2200',
  },
  {
    id: 'WT-88208',
    customerId: 'CUST-1005',
    customerName: 'Dr. Sunita Shukla',
    type: 'Credit',
    amount: 500,
    date: '2026-10-02 16:30:00',
    reason: 'Manual cash collection by rider Ramesh Verma',
    method: 'Manual Support',
    referenceId: 'CASH-REC-RV-04',
  }
];

export const MOCK_RECONCILIATION: RazorpayReconciliation[] = [
  {
    id: 'SETTL-2026-1004',
    payoutId: 'pout_Oca910928a',
    settlementDate: '2026-10-04',
    grossCollected: 48600,
    platformFees: 972,
    gstOnFees: 175,
    netSettled: 47453,
    walletFloatCredited: 48600,
    status: 'Matched',
    transactionCount: 38,
  },
  {
    id: 'SETTL-2026-1003',
    payoutId: 'pout_Obz829101b',
    settlementDate: '2026-10-03',
    grossCollected: 52400,
    platformFees: 1048,
    gstOnFees: 189,
    netSettled: 51163,
    walletFloatCredited: 52400,
    status: 'Matched',
    transactionCount: 42,
  },
  {
    id: 'SETTL-2026-1002',
    payoutId: 'pout_Oay718290c',
    settlementDate: '2026-10-02',
    grossCollected: 41200,
    platformFees: 824,
    gstOnFees: 148,
    netSettled: 40228,
    walletFloatCredited: 41200,
    status: 'Matched',
    transactionCount: 31,
  },
  {
    id: 'SETTL-2026-1001',
    payoutId: 'pout_Oax607182d',
    settlementDate: '2026-10-01',
    grossCollected: 64800,
    platformFees: 1296,
    gstOnFees: 233,
    netSettled: 63271,
    walletFloatCredited: 64800,
    status: 'Matched',
    transactionCount: 54,
  }
];

export const MOCK_SERVICE_AREAS: ServiceAreaInfo[] = [
  {
    id: 'AREA-01',
    name: 'Shankar Nagar',
    pincode: '492007',
    status: 'Active',
    activeSubscribers: 42,
    dailyDemandLiters: 88,
    morningWindow: '06:00 AM - 07:30 AM',
    assignedRider: 'Ramesh Verma',
  },
  {
    id: 'AREA-02',
    name: 'Telibandha',
    pincode: '492006',
    status: 'Active',
    activeSubscribers: 36,
    dailyDemandLiters: 74,
    morningWindow: '06:15 AM - 07:45 AM',
    assignedRider: 'Karan Sahu',
  },
  {
    id: 'AREA-03',
    name: 'Samta Colony',
    pincode: '492001',
    status: 'Active',
    activeSubscribers: 38,
    dailyDemandLiters: 79,
    morningWindow: '05:45 AM - 07:15 AM',
    assignedRider: 'Bhupendra Dewangan',
  },
  {
    id: 'AREA-04',
    name: 'Pandri',
    pincode: '492004',
    status: 'Active',
    activeSubscribers: 28,
    dailyDemandLiters: 56,
    morningWindow: '06:30 AM - 08:00 AM',
    assignedRider: 'Manoj Baghel',
  },
  {
    id: 'AREA-05',
    name: 'Civil Lines',
    pincode: '492001',
    status: 'Active',
    activeSubscribers: 31,
    dailyDemandLiters: 68,
    morningWindow: '05:45 AM - 07:15 AM',
    assignedRider: 'Sunil Yadav',
  },
  {
    id: 'AREA-06',
    name: 'Devendra Nagar',
    pincode: '492004',
    status: 'Active',
    activeSubscribers: 29,
    dailyDemandLiters: 64,
    morningWindow: '06:00 AM - 07:30 AM',
    assignedRider: 'Dinesh Kurre',
  },
  {
    id: 'AREA-07',
    name: 'Tatibandh',
    pincode: '492099',
    status: 'Active',
    activeSubscribers: 19,
    dailyDemandLiters: 42,
    morningWindow: '06:30 AM - 08:30 AM',
    assignedRider: 'Unassigned',
  },
  {
    id: 'AREA-08',
    name: 'Pachpedi Naka',
    pincode: '492001',
    status: 'Active',
    activeSubscribers: 18,
    dailyDemandLiters: 38,
    morningWindow: '06:30 AM - 08:30 AM',
    assignedRider: 'Unassigned',
  },
  {
    id: 'AREA-09',
    name: 'VIP Road',
    pincode: '492015',
    status: 'Active',
    activeSubscribers: 22,
    dailyDemandLiters: 45,
    morningWindow: '06:15 AM - 07:45 AM',
    assignedRider: 'Amit Tandi',
  }
];

export const MOCK_PLANS: SubscriptionPlanItem[] = [
  {
    id: 'PLAN-101',
    customerId: 'CUST-1001',
    customerName: 'Ananya Sharma',
    phone: '+91 98261 44521',
    area: 'Shankar Nagar',
    product: 'A2 Desi Gir Cow Milk',
    quantity: '2 Liters / day',
    frequency: 'Daily',
    status: 'Active',
    startDate: '2025-08-12',
    dailyValue: 180,
  },
  {
    id: 'PLAN-102',
    customerId: 'CUST-1003',
    customerName: 'Priyanka Dewangan',
    phone: '+91 97555 19022',
    area: 'Civil Lines',
    product: 'A2 Desi Cow Milk (Trial Pack)',
    quantity: '1.5 Liters / day',
    frequency: '7-Day Trial',
    status: 'Active',
    startDate: '2026-09-28',
    trialDaysRemaining: 1,
    dailyValue: 135,
  },
  {
    id: 'PLAN-103',
    customerId: 'CUST-1004',
    customerName: 'Rajesh Baghel',
    phone: '+91 98271 63490',
    area: 'Samta Colony',
    product: 'A2 Desi Cow Milk + Paneer',
    quantity: '2 Liters Milk (Alt Days)',
    frequency: 'Alternate Days',
    status: 'Active',
    startDate: '2025-05-19',
    dailyValue: 180,
  },
  {
    id: 'PLAN-104',
    customerId: 'CUST-1007',
    customerName: 'Kavita Verma',
    phone: '+91 97520 33411',
    area: 'VIP Road',
    product: 'A2 Desi Cow Milk',
    quantity: '3 Liters / day',
    frequency: 'Daily',
    status: 'Active',
    startDate: '2025-04-01',
    dailyValue: 270,
  },
  {
    id: 'PLAN-105',
    customerId: 'CUST-1008',
    customerName: 'Abhishek Singhania',
    phone: '+91 98930 11200',
    area: 'Shankar Nagar',
    product: 'A2 Desi Cow Milk (Trial Pack)',
    quantity: '1 Liter / day',
    frequency: '7-Day Trial',
    status: 'Active',
    startDate: '2026-10-01',
    trialDaysRemaining: 4,
    dailyValue: 90,
  },
  {
    id: 'PLAN-106',
    customerId: 'CUST-1010',
    customerName: 'Nitin Pande',
    phone: '+91 96172 09843',
    area: 'Pachpedi Naka',
    product: 'A2 Desi Cow Milk',
    quantity: '1.5 Liters / day',
    frequency: 'Daily',
    status: 'Paused',
    startDate: '2025-06-30',
    dailyValue: 135,
  },
  {
    id: 'PLAN-107',
    customerId: 'CUST-1012',
    customerName: 'Suresh Banchhor',
    phone: '+91 94241 62901',
    area: 'Telibandha',
    product: 'A2 Desi Cow Milk (Trial Pack)',
    quantity: '1 Liter / day',
    frequency: '7-Day Trial',
    status: 'Active',
    startDate: '2026-09-30',
    trialDaysRemaining: 3,
    dailyValue: 90,
  }
];

export const MOCK_AUDIT_LOGS: AuditLogItem[] = [
  {
    id: 'LOG-9921',
    timestamp: '2026-10-04 22:00:01',
    actor: 'System Automated Engine',
    category: 'Nightly Cutoff',
    action: '10:00 PM Order Generation Batch Executed',
    details: '286 subscription orders processed for 05 Oct morning. 482 L bulk milk locked. 2 orders skipped due to low balance (<₹180).'
  },
  {
    id: 'LOG-9920',
    timestamp: '2026-10-04 21:45:10',
    actor: 'Amit Sharma (Ops Lead)',
    category: 'Rider Assignment',
    action: 'Assigned Amit Tandi to VIP Road Route',
    details: 'VIP Road Route (ROUTE-VIP) reassigned to Rider Amit Tandi (CG 04 QM 5501).'
  },
  {
    id: 'LOG-9919',
    timestamp: '2026-10-04 18:30:22',
    actor: 'Pooja Verma (Inventory)',
    category: 'Inventory Update',
    action: 'Evening Pasteurization Batch Added',
    details: 'Added 520 Liters of A2 Milk batch (PF-MILK-OCT05-AM) to Shankar Nagar cold room.'
  },
  {
    id: 'LOG-9918',
    timestamp: '2026-10-04 16:15:00',
    actor: 'Customer Support Bot',
    category: 'Wallet Adjustment',
    action: 'Sent 34 Low-Balance WhatsApp Alerts',
    details: 'Triggered automated recharge reminders for customers with balance < ₹250 before 10 PM cutoff.'
  },
  {
    id: 'LOG-9917',
    timestamp: '2026-10-03 19:00:00',
    actor: 'Amit Sharma (Ops Lead)',
    category: 'Pricing',
    action: 'Updated Bilona Ghee 1L Price',
    details: 'Revised A2 Vedic Bilona Ghee 1L jar rate to ₹1,850 based on festive organic batch harvest.'
  }
];

export const DASHBOARD_STATS = {
  tomorrowMilkLitersNeeded: 482,
  currentMilkStockLiters: 520,
  activeSubscriptionsCount: 263,
  activeTrialsCount: 38,
  ridersAssignedCount: 7,
  activeRoutesCount: 9,
  unassignedRoutesCount: 2,
  totalWalletFloat: 384500,
  customersNeedingRechargeCount: 19,
  deliveryDeadline: '09:00 AM',
  cutoffTime: '10:00 PM'
};
